name             'role-sphinx'
maintainer       'Stephen Van Zee'
maintainer_email 'svanzee@caringbridge.org'
license          'All rights reserved'
description      'Installs/Configures role-sphinx'
long_description 'Installs/Configures role-sphinx'
version          '0.1.1'

depends 'sphinx'
depends 'yum-epel'
