default[:sphinx][:install_method] = 'rpm'
default[:sphinx][:rpm][:conf_path] = '/var/www/platform/config/sphinx.conf'
# default[:sphinx][:rpm][:name] = "sphinx-2.2.3-1.rhel6.x86_64.rpm"
default[:sphinx][:rpm][:name] = "sphinx-2.0.8-1.rhel6.x86_64.rpm"
default[:sphinx][:rpm][:base_url] = "http://sphinxsearch.com/files/"
default[:sphinx][:package][:name] = nil # depends on platform_family when not explicit
default[:sphinx][:package][:yum_repo] = 'yum-epel' # yum recipe or nil
default[:sphinx][:user] = 'root'
default[:sphinx][:group] = 'root'
default[:sphinx][:use_mysql]      = false
default[:sphinx][:use_percona]    = false
default[:sphinx][:use_postgres]   = false
default[:sphinx][:config_file] = '/var/www/platform/config/sphinx.conf'
